"""add upload sessions and large inputs

Revision ID: 300e6a10b400
Revises: 553de899ddc9
Create Date: 2026-06-02 02:14:12.788564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '300e6a10b400'
down_revision: str | Sequence[str] | None = '553de899ddc9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('uploader_type', sa.String(length=16), nullable=False),
    sa.Column('uploader_id', sa.String(length=36), nullable=False),
    sa.Column('uploader_name', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('effective_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('expected_size', sa.BigInteger(), nullable=False),
    sa.Column('received_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=96), nullable=False),
    sa.Column('upload_mode', sa.String(length=32), nullable=False),
    sa.Column('storage_backend', sa.String(length=32), nullable=False),
    sa.Column('provider_upload_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('part_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('part_count', sa.Integer(), nullable=False),
    sa.Column('quota_reservation_id', sa.String(length=36), nullable=True),
    sa.Column('parent_path', sa.String(length=1024), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('retention_policy', sa.String(length=32), nullable=False),
    sa.Column('conflict_strategy', sa.String(length=32), nullable=False),
    sa.Column('expected_existing_file_id', sa.String(length=36), nullable=True),
    sa.Column('client_request_id', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_deleted_at'), 'upload_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_upload_sessions_workspace_id'), 'upload_sessions', ['workspace_id'], unique=False)
    op.create_index('ix_upload_sessions_ws_status_expires', 'upload_sessions', ['workspace_id', 'status', 'expires_at'], unique=False)
    op.create_index('ix_upload_sessions_ws_surface_status_created', 'upload_sessions', ['workspace_id', 'surface', 'status', 'created_at'], unique=False)
    op.create_index('uq_upload_sessions_client_request_active', 'upload_sessions', ['workspace_id', 'uploader_type', 'uploader_id', 'client_request_id'], unique=True, postgresql_where=sa.text("deleted_at IS NULL AND client_request_id IS NOT NULL AND status IN ('pending', 'uploading')"))
    op.create_table('upload_parts',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=96), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('presigned_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['upload_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_parts_deleted_at'), 'upload_parts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_upload_parts_session_id'), 'upload_parts', ['session_id'], unique=False)
    op.create_index('ix_upload_parts_session_status', 'upload_parts', ['session_id', 'status'], unique=False)
    op.create_index(op.f('ix_upload_parts_workspace_id'), 'upload_parts', ['workspace_id'], unique=False)
    op.create_index('ix_upload_parts_workspace_session', 'upload_parts', ['workspace_id', 'session_id'], unique=False)
    op.create_index('uq_upload_parts_active_part', 'upload_parts', ['session_id', 'part_number'], unique=True, postgresql_where=sa.text("deleted_at IS NULL AND status IN ('signed', 'uploaded')"))
    op.create_table('upload_quota_reservations',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('surface', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('reserved_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_source', sa.String(length=32), nullable=False),
    sa.Column('committed_file_id', sa.String(length=36), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['upload_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upload_quota_reservations_committed_file', 'upload_quota_reservations', ['committed_source', 'committed_file_id'], unique=False)
    op.create_index(op.f('ix_upload_quota_reservations_deleted_at'), 'upload_quota_reservations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_upload_quota_reservations_session_id'), 'upload_quota_reservations', ['session_id'], unique=False)
    op.create_index(op.f('ix_upload_quota_reservations_workspace_id'), 'upload_quota_reservations', ['workspace_id'], unique=False)
    op.create_index('ix_upload_quota_reservations_ws_status_expires', 'upload_quota_reservations', ['workspace_id', 'status', 'expires_at'], unique=False)
    op.create_index('uq_upload_quota_reservation_session_active', 'upload_quota_reservations', ['session_id'], unique=True, postgresql_where=sa.text("deleted_at IS NULL AND status = 'active' AND session_id IS NOT NULL"))
    op.create_table('workspace_large_input_files',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('upload_session_id', sa.String(length=36), nullable=True),
    sa.Column('uploader_type', sa.String(length=16), nullable=False),
    sa.Column('uploader_id', sa.String(length=36), nullable=False),
    sa.Column('uploader_name', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('retention_policy', sa.String(length=32), nullable=False),
    sa.Column('retention_anchor_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('checksum', sa.String(length=96), nullable=False),
    sa.Column('scan_status', sa.String(length=32), nullable=False),
    sa.Column('scan_reason', sa.String(length=255), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_session_id'], ['upload_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_large_input_files_active_source', 'workspace_large_input_files', ['workspace_id', 'id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_workspace_large_input_files_deleted_at'), 'workspace_large_input_files', ['deleted_at'], unique=False)
    op.create_index('ix_workspace_large_input_files_owner', 'workspace_large_input_files', ['workspace_id', 'owner_type', 'owner_id'], unique=False)
    op.create_index(op.f('ix_workspace_large_input_files_upload_session_id'), 'workspace_large_input_files', ['upload_session_id'], unique=False)
    op.create_index(op.f('ix_workspace_large_input_files_workspace_id'), 'workspace_large_input_files', ['workspace_id'], unique=False)
    op.create_index('ix_workspace_large_input_files_ws_status', 'workspace_large_input_files', ['workspace_id', 'status'], unique=False)
    op.add_column('blackboard_files', sa.Column('checksum', sa.String(length=96), server_default='', nullable=False))
    op.add_column('blackboard_files', sa.Column('scan_status', sa.String(length=32), server_default='skipped', nullable=False))
    op.add_column('blackboard_files', sa.Column('scan_reason', sa.String(length=255), server_default='legacy_file', nullable=False))
    op.add_column('blackboard_files', sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('blackboard_files', 'file_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('workspace_files', sa.Column('checksum', sa.String(length=96), server_default='', nullable=False))
    op.add_column('workspace_files', sa.Column('scan_status', sa.String(length=32), server_default='skipped', nullable=False))
    op.add_column('workspace_files', sa.Column('scan_reason', sa.String(length=255), server_default='legacy_file', nullable=False))
    op.add_column('workspace_files', sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('workspace_files', 'file_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_files', 'file_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('workspace_files', 'scanned_at')
    op.drop_column('workspace_files', 'scan_reason')
    op.drop_column('workspace_files', 'scan_status')
    op.drop_column('workspace_files', 'checksum')
    op.alter_column('blackboard_files', 'file_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('blackboard_files', 'scanned_at')
    op.drop_column('blackboard_files', 'scan_reason')
    op.drop_column('blackboard_files', 'scan_status')
    op.drop_column('blackboard_files', 'checksum')
    op.drop_index('ix_workspace_large_input_files_ws_status', table_name='workspace_large_input_files')
    op.drop_index(op.f('ix_workspace_large_input_files_workspace_id'), table_name='workspace_large_input_files')
    op.drop_index(op.f('ix_workspace_large_input_files_upload_session_id'), table_name='workspace_large_input_files')
    op.drop_index('ix_workspace_large_input_files_owner', table_name='workspace_large_input_files')
    op.drop_index(op.f('ix_workspace_large_input_files_deleted_at'), table_name='workspace_large_input_files')
    op.drop_index('ix_workspace_large_input_files_active_source', table_name='workspace_large_input_files', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('workspace_large_input_files')
    op.drop_index('uq_upload_quota_reservation_session_active', table_name='upload_quota_reservations', postgresql_where=sa.text("deleted_at IS NULL AND status = 'active' AND session_id IS NOT NULL"))
    op.drop_index('ix_upload_quota_reservations_ws_status_expires', table_name='upload_quota_reservations')
    op.drop_index(op.f('ix_upload_quota_reservations_workspace_id'), table_name='upload_quota_reservations')
    op.drop_index(op.f('ix_upload_quota_reservations_session_id'), table_name='upload_quota_reservations')
    op.drop_index(op.f('ix_upload_quota_reservations_deleted_at'), table_name='upload_quota_reservations')
    op.drop_index('ix_upload_quota_reservations_committed_file', table_name='upload_quota_reservations')
    op.drop_table('upload_quota_reservations')
    op.drop_index('uq_upload_parts_active_part', table_name='upload_parts', postgresql_where=sa.text("deleted_at IS NULL AND status IN ('signed', 'uploaded')"))
    op.drop_index('ix_upload_parts_workspace_session', table_name='upload_parts')
    op.drop_index(op.f('ix_upload_parts_workspace_id'), table_name='upload_parts')
    op.drop_index('ix_upload_parts_session_status', table_name='upload_parts')
    op.drop_index(op.f('ix_upload_parts_session_id'), table_name='upload_parts')
    op.drop_index(op.f('ix_upload_parts_deleted_at'), table_name='upload_parts')
    op.drop_table('upload_parts')
    op.drop_index('uq_upload_sessions_client_request_active', table_name='upload_sessions', postgresql_where=sa.text("deleted_at IS NULL AND client_request_id IS NOT NULL AND status IN ('pending', 'uploading')"))
    op.drop_index('ix_upload_sessions_ws_surface_status_created', table_name='upload_sessions')
    op.drop_index('ix_upload_sessions_ws_status_expires', table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_workspace_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_deleted_at'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
