"""add file references and agent grants

Revision ID: 553de899ddc9
Revises: 30a1bcac4c80
Create Date: 2026-06-01 20:52:13.289949

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '553de899ddc9'
down_revision: str | Sequence[str] | None = '30a1bcac4c80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_message_file_references',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('scan_status', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['workspace_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_message_file_references_deleted_at'), 'workspace_message_file_references', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspace_message_file_references_message_id'), 'workspace_message_file_references', ['message_id'], unique=False)
    op.create_index(op.f('ix_workspace_message_file_references_workspace_id'), 'workspace_message_file_references', ['workspace_id'], unique=False)
    op.create_index('ix_workspace_msg_file_ref_source', 'workspace_message_file_references', ['workspace_id', 'source', 'file_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_workspace_msg_file_ref_active', 'workspace_message_file_references', ['message_id', 'source', 'file_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('agent_file_access_grants',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('file_reference_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_agent_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=36), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_reference_id'], ['workspace_message_file_references.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['workspace_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_agent_id'], ['instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_file_access_grants_deleted_at'), 'agent_file_access_grants', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_file_access_grants_file_reference_id'), 'agent_file_access_grants', ['file_reference_id'], unique=False)
    op.create_index(op.f('ix_agent_file_access_grants_message_id'), 'agent_file_access_grants', ['message_id'], unique=False)
    op.create_index(op.f('ix_agent_file_access_grants_recipient_agent_id'), 'agent_file_access_grants', ['recipient_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_file_access_grants_workspace_id'), 'agent_file_access_grants', ['workspace_id'], unique=False)
    op.create_index('ix_agent_file_grants_recipient', 'agent_file_access_grants', ['workspace_id', 'recipient_agent_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_agent_file_grants_source', 'agent_file_access_grants', ['workspace_id', 'source', 'file_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_agent_file_grants_active', 'agent_file_access_grants', ['file_reference_id', 'recipient_agent_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_agent_file_grants_active', table_name='agent_file_access_grants', postgresql_where=sa.text('deleted_at IS NULL AND revoked_at IS NULL'))
    op.drop_index('ix_agent_file_grants_source', table_name='agent_file_access_grants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_agent_file_grants_recipient', table_name='agent_file_access_grants', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_agent_file_access_grants_workspace_id'), table_name='agent_file_access_grants')
    op.drop_index(op.f('ix_agent_file_access_grants_recipient_agent_id'), table_name='agent_file_access_grants')
    op.drop_index(op.f('ix_agent_file_access_grants_message_id'), table_name='agent_file_access_grants')
    op.drop_index(op.f('ix_agent_file_access_grants_file_reference_id'), table_name='agent_file_access_grants')
    op.drop_index(op.f('ix_agent_file_access_grants_deleted_at'), table_name='agent_file_access_grants')
    op.drop_table('agent_file_access_grants')
    op.drop_index('uq_workspace_msg_file_ref_active', table_name='workspace_message_file_references', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_workspace_msg_file_ref_source', table_name='workspace_message_file_references', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_workspace_message_file_references_workspace_id'), table_name='workspace_message_file_references')
    op.drop_index(op.f('ix_workspace_message_file_references_message_id'), table_name='workspace_message_file_references')
    op.drop_index(op.f('ix_workspace_message_file_references_deleted_at'), table_name='workspace_message_file_references')
    op.drop_table('workspace_message_file_references')
    # ### end Alembic commands ###
