"""add file scan and delete jobs

Revision ID: 64b548305e03
Revises: 300e6a10b400
Create Date: 2026-06-02 02:45:04.243095

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '64b548305e03'
down_revision: str | Sequence[str] | None = '300e6a10b400'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_scan_jobs',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leased_by', sa.String(length=128), nullable=False),
    sa.Column('leased_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_scan_jobs_deleted_at'), 'file_scan_jobs', ['deleted_at'], unique=False)
    op.create_index('ix_file_scan_jobs_pending', 'file_scan_jobs', ['status', 'next_attempt_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_file_scan_jobs_source', 'file_scan_jobs', ['workspace_id', 'source', 'file_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_file_scan_jobs_workspace_id'), 'file_scan_jobs', ['workspace_id'], unique=False)
    op.create_index('uq_file_scan_jobs_active_source', 'file_scan_jobs', ['source', 'file_id'], unique=True, postgresql_where=sa.text("deleted_at IS NULL AND status IN ('pending', 'leased')"))
    op.create_table('storage_object_delete_jobs',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_object_delete_jobs_deleted_at'), 'storage_object_delete_jobs', ['deleted_at'], unique=False)
    op.create_index('ix_storage_object_delete_jobs_pending', 'storage_object_delete_jobs', ['status', 'next_attempt_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_storage_object_delete_jobs_source', 'storage_object_delete_jobs', ['workspace_id', 'source', 'source_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_storage_object_delete_jobs_workspace_id'), 'storage_object_delete_jobs', ['workspace_id'], unique=False)
    op.create_index('uq_storage_object_delete_jobs_active', 'storage_object_delete_jobs', ['source', 'source_id', 'storage_key'], unique=True, postgresql_where=sa.text("deleted_at IS NULL AND status IN ('pending', 'retrying')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_storage_object_delete_jobs_active', table_name='storage_object_delete_jobs', postgresql_where=sa.text("deleted_at IS NULL AND status IN ('pending', 'retrying')"))
    op.drop_index(op.f('ix_storage_object_delete_jobs_workspace_id'), table_name='storage_object_delete_jobs')
    op.drop_index('ix_storage_object_delete_jobs_source', table_name='storage_object_delete_jobs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_storage_object_delete_jobs_pending', table_name='storage_object_delete_jobs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_storage_object_delete_jobs_deleted_at'), table_name='storage_object_delete_jobs')
    op.drop_table('storage_object_delete_jobs')
    op.drop_index('uq_file_scan_jobs_active_source', table_name='file_scan_jobs', postgresql_where=sa.text("deleted_at IS NULL AND status IN ('pending', 'leased')"))
    op.drop_index(op.f('ix_file_scan_jobs_workspace_id'), table_name='file_scan_jobs')
    op.drop_index('ix_file_scan_jobs_source', table_name='file_scan_jobs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_file_scan_jobs_pending', table_name='file_scan_jobs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_file_scan_jobs_deleted_at'), table_name='file_scan_jobs')
    op.drop_table('file_scan_jobs')
    # ### end Alembic commands ###
