"""hermes_v216_worker_and_artifact_fields

Revision ID: 8e08c3453daf
Revises: 08837b4eb7b1
Create Date: 2026-06-06 19:08:45.286422

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e08c3453daf'
down_revision: str | Sequence[str] | None = '08837b4eb7b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hermes_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('task_no', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=255), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=255), nullable=True),
    sa.Column('installation_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'ACCEPTED', 'RUNNING', 'WAITING_APPROVAL', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT', name='taskstatus'), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('arguments_hash', sa.String(length=64), nullable=True),
    sa.Column('request_summary', sa.String(length=500), nullable=True),
    sa.Column('result_summary', sa.String(length=500), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('hermes_run_id', sa.String(length=255), nullable=True),
    sa.Column('event_url', sa.String(length=1024), nullable=True),
    sa.Column('artifact_url', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('dispatch_status', sa.String(length=32), nullable=True),
    sa.Column('dispatch_attempts', sa.Integer(), nullable=False),
    sa.Column('last_dispatch_error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('run_started_at', sa.DateTime(), nullable=True),
    sa.Column('run_finished_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hermes_tasks_deleted_at'), 'hermes_tasks', ['deleted_at'], unique=False)
    op.create_index('ix_hermes_tasks_org_agent', 'hermes_tasks', ['org_id', 'agent_id'], unique=False)
    op.create_index('ix_hermes_tasks_org_skill', 'hermes_tasks', ['org_id', 'skill_id'], unique=False)
    op.create_index('ix_hermes_tasks_org_status', 'hermes_tasks', ['org_id', 'status'], unique=False)
    op.create_index('ix_hermes_tasks_queue_status_created_at', 'hermes_tasks', ['org_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_hermes_tasks_worker_lock', 'hermes_tasks', ['status', 'locked_at'], unique=False)
    op.create_index('uq_hermes_tasks_task_no_alive', 'hermes_tasks', ['task_no'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('hermes_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('skill_id', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_type', sa.String(length=32), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('permission_scope', sa.String(length=32), nullable=False),
    sa.Column('download_url', sa.String(length=1024), nullable=True),
    sa.Column('preview_supported', sa.Boolean(), nullable=False),
    sa.Column('source_run_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['hermes_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hermes_artifacts_content_type', 'hermes_artifacts', ['content_type'], unique=False)
    op.create_index(op.f('ix_hermes_artifacts_deleted_at'), 'hermes_artifacts', ['deleted_at'], unique=False)
    op.create_index('ix_hermes_artifacts_org_scope', 'hermes_artifacts', ['org_id', 'permission_scope'], unique=False)
    op.create_index('ix_hermes_artifacts_org_task', 'hermes_artifacts', ['org_id', 'task_id'], unique=False)
    op.create_index('ix_hermes_artifacts_workspace', 'hermes_artifacts', ['workspace_id'], unique=False)
    op.create_table('hermes_task_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('TASK_CREATED', 'TASK_QUEUED', 'TASK_ACCEPTED', 'TASK_STARTED', 'TASK_RETRYING', 'TASK_CANCEL_REQUESTED', 'TASK_COMPLETED', 'TASK_FAILED', 'TASK_CANCELLED', 'TASK_TIMEOUT', 'HERMES_RUN_CREATED', 'HERMES_RUN_STARTED', 'HERMES_RUN_DELTA', 'HERMES_RUN_COMPLETED', 'HERMES_RUN_FAILED', 'ARTIFACT_SCAN_STARTED', 'ARTIFACT_CREATED', 'ARTIFACT_SCAN_COMPLETED', 'ARTIFACT_SCAN_FAILED', 'ARTIFACT_PERMISSION_CHANGED', 'ARTIFACT_SHARED', 'ARTIFACT_DELETED', name='eventtype'), nullable=False),
    sa.Column('event_seq', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['hermes_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hermes_task_events_task_seq', 'hermes_task_events', ['task_id', 'event_seq'], unique=False)
    op.create_index('uq_hermes_task_events_task_seq', 'hermes_task_events', ['task_id', 'event_seq'], unique=True)
    op.create_table('artifact_download_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses_remaining', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['hermes_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adt_artifact_id', 'artifact_download_tokens', ['artifact_id'], unique=False)
    op.create_index('ix_adt_org_id', 'artifact_download_tokens', ['org_id'], unique=False)
    op.create_index(op.f('ix_artifact_download_tokens_deleted_at'), 'artifact_download_tokens', ['deleted_at'], unique=False)
    op.create_index('uq_adt_token_alive', 'artifact_download_tokens', ['token'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('artifact_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('permission_level', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['hermes_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ap_artifact_id', 'artifact_permissions', ['artifact_id'], unique=False)
    op.create_index('ix_ap_user_id', 'artifact_permissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_artifact_permissions_deleted_at'), 'artifact_permissions', ['deleted_at'], unique=False)
    op.create_index('uq_ap_artifact_user_alive', 'artifact_permissions', ['artifact_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_hermes_coll_skill_deleted_at'), table_name='hermes_collection_skills')
    op.create_index(op.f('ix_hermes_collection_skills_deleted_at'), 'hermes_collection_skills', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_hermes_skill_coll_deleted_at'), table_name='hermes_skill_collections')
    op.create_index(op.f('ix_hermes_skill_collections_deleted_at'), 'hermes_skill_collections', ['deleted_at'], unique=False)
    op.add_column('hermes_skill_installations', sa.Column('target_agent_type', sa.String(length=64), nullable=True))
    op.add_column('hermes_skill_installations', sa.Column('conflict_strategy', sa.String(length=32), nullable=True))
    op.add_column('hermes_skill_installations', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('hermes_skill_installations', sa.Column('install_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('hermes_skill_installations', sa.Column('profile_root_path', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_hermes_skill_inst_deleted_at'), table_name='hermes_skill_installations')
    op.create_index(op.f('ix_hermes_skill_installations_deleted_at'), 'hermes_skill_installations', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_hermes_skill_reg_deleted_at'), table_name='hermes_skill_registries')
    op.create_index(op.f('ix_hermes_skill_registries_deleted_at'), 'hermes_skill_registries', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hermes_skill_registries_deleted_at'), table_name='hermes_skill_registries')
    op.create_index(op.f('ix_hermes_skill_reg_deleted_at'), 'hermes_skill_registries', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_hermes_skill_installations_deleted_at'), table_name='hermes_skill_installations')
    op.create_index(op.f('ix_hermes_skill_inst_deleted_at'), 'hermes_skill_installations', ['deleted_at'], unique=False)
    op.drop_column('hermes_skill_installations', 'profile_root_path')
    op.drop_column('hermes_skill_installations', 'install_metadata')
    op.drop_column('hermes_skill_installations', 'last_synced_at')
    op.drop_column('hermes_skill_installations', 'conflict_strategy')
    op.drop_column('hermes_skill_installations', 'target_agent_type')
    op.drop_index(op.f('ix_hermes_skill_collections_deleted_at'), table_name='hermes_skill_collections')
    op.create_index(op.f('ix_hermes_skill_coll_deleted_at'), 'hermes_skill_collections', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_hermes_collection_skills_deleted_at'), table_name='hermes_collection_skills')
    op.create_index(op.f('ix_hermes_coll_skill_deleted_at'), 'hermes_collection_skills', ['deleted_at'], unique=False)
    op.drop_index('uq_ap_artifact_user_alive', table_name='artifact_permissions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_artifact_permissions_deleted_at'), table_name='artifact_permissions')
    op.drop_index('ix_ap_user_id', table_name='artifact_permissions')
    op.drop_index('ix_ap_artifact_id', table_name='artifact_permissions')
    op.drop_table('artifact_permissions')
    op.drop_index('uq_adt_token_alive', table_name='artifact_download_tokens', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_artifact_download_tokens_deleted_at'), table_name='artifact_download_tokens')
    op.drop_index('ix_adt_org_id', table_name='artifact_download_tokens')
    op.drop_index('ix_adt_artifact_id', table_name='artifact_download_tokens')
    op.drop_table('artifact_download_tokens')
    op.drop_index('uq_hermes_task_events_task_seq', table_name='hermes_task_events')
    op.drop_index('ix_hermes_task_events_task_seq', table_name='hermes_task_events')
    op.drop_table('hermes_task_events')
    op.drop_index('ix_hermes_artifacts_workspace', table_name='hermes_artifacts')
    op.drop_index('ix_hermes_artifacts_org_task', table_name='hermes_artifacts')
    op.drop_index('ix_hermes_artifacts_org_scope', table_name='hermes_artifacts')
    op.drop_index(op.f('ix_hermes_artifacts_deleted_at'), table_name='hermes_artifacts')
    op.drop_index('ix_hermes_artifacts_content_type', table_name='hermes_artifacts')
    op.drop_table('hermes_artifacts')
    op.drop_index('uq_hermes_tasks_task_no_alive', table_name='hermes_tasks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_hermes_tasks_worker_lock', table_name='hermes_tasks')
    op.drop_index('ix_hermes_tasks_queue_status_created_at', table_name='hermes_tasks')
    op.drop_index('ix_hermes_tasks_org_status', table_name='hermes_tasks')
    op.drop_index('ix_hermes_tasks_org_skill', table_name='hermes_tasks')
    op.drop_index('ix_hermes_tasks_org_agent', table_name='hermes_tasks')
    op.drop_index(op.f('ix_hermes_tasks_deleted_at'), table_name='hermes_tasks')
    op.drop_table('hermes_tasks')
    # ### end Alembic commands ###
