"""Task Orchestrator Enums - Type-safe enumerations for workflow states."""

from enum import Enum

from app.modules.task_orchestrator.constants import (
    WORKFLOW_STATUS_CREATED,
    WORKFLOW_STATUS_RUNNING,
    WORKFLOW_STATUS_PAUSED,
    WORKFLOW_STATUS_WAITING_HUMAN,
    WORKFLOW_STATUS_BLOCKED,
    WORKFLOW_STATUS_COMPLETED,
    WORKFLOW_STATUS_FAILED,
    WORKFLOW_STATUS_CANCELLED,
    NODE_STATUS_PENDING,
    NODE_STATUS_RUNNING,
    NODE_STATUS_WAITING_HUMAN,
    NODE_STATUS_BLOCKED,
    NODE_STATUS_COMPLETED,
    NODE_STATUS_FAILED,
    NODE_STATUS_CANCELLED,
    NODE_STATUS_TIMEOUT,
    NODE_TYPE_ROLE_TASK,
    NODE_TYPE_SYSTEM_TASK,
    NODE_TYPE_HUMAN_REVIEW,
    NODE_TYPE_GATEWAY_TASK,
    EXECUTOR_TYPE_OPENCLAW,
    EXECUTOR_TYPE_DIFY,
    EXECUTOR_TYPE_DEERFLOW,
    EXECUTOR_TYPE_HUMAN_REVIEW,
    EXECUTOR_TYPE_SYSTEM,
    INTERVENTION_TYPE_APPROVE,
    INTERVENTION_TYPE_REJECT,
    INTERVENTION_TYPE_MODIFY,
    INTERVENTION_TYPE_COMMENT,
    INTERVENTION_TYPE_ESCALATE,
    INTERVENTION_STATUS_PENDING,
    INTERVENTION_STATUS_RESOLVED,
    INTERVENTION_STATUS_CANCELLED,
    SOURCE_TYPE_PAPERCLIP_ISSUE,
    SOURCE_TYPE_PORTAL,
    SOURCE_TYPE_API,
    SOURCE_TYPE_EVENT,
    TEMPLATE_STATUS_DRAFT,
    TEMPLATE_STATUS_ACTIVE,
    TEMPLATE_STATUS_DEPRECATED,
    EDGE_CONDITION_ALWAYS,
    EDGE_CONDITION_SUCCESS,
    EDGE_CONDITION_FAILURE,
    EDGE_CONDITION_MANUAL_GATE,
    EDGE_CONDITION_EXPR,
    CALLBACK_MODE_POLL,
    CALLBACK_MODE_WEBHOOK,
    CALLBACK_MODE_INTERRUPT,
)


class WorkflowStatus(str, Enum):
    """Workflow instance lifecycle states."""

    CREATED = WORKFLOW_STATUS_CREATED
    RUNNING = WORKFLOW_STATUS_RUNNING
    PAUSED = WORKFLOW_STATUS_PAUSED
    WAITING_HUMAN = WORKFLOW_STATUS_WAITING_HUMAN
    BLOCKED = WORKFLOW_STATUS_BLOCKED
    COMPLETED = WORKFLOW_STATUS_COMPLETED
    FAILED = WORKFLOW_STATUS_FAILED
    CANCELLED = WORKFLOW_STATUS_CANCELLED


class NodeStatus(str, Enum):
    """Workflow node execution states."""

    PENDING = NODE_STATUS_PENDING
    RUNNING = NODE_STATUS_RUNNING
    WAITING_HUMAN = NODE_STATUS_WAITING_HUMAN
    BLOCKED = NODE_STATUS_BLOCKED
    COMPLETED = NODE_STATUS_COMPLETED
    FAILED = NODE_STATUS_FAILED
    CANCELLED = NODE_STATUS_CANCELLED
    TIMEOUT = NODE_STATUS_TIMEOUT


class NodeType(str, Enum):
    """Workflow node types."""

    ROLE_TASK = NODE_TYPE_ROLE_TASK
    SYSTEM_TASK = NODE_TYPE_SYSTEM_TASK
    HUMAN_REVIEW = NODE_TYPE_HUMAN_REVIEW
    GATEWAY_TASK = NODE_TYPE_GATEWAY_TASK


class ExecutorType(str, Enum):
    """Executor backend types."""

    OPENCLAW = EXECUTOR_TYPE_OPENCLAW
    DIFY = EXECUTOR_TYPE_DIFY
    DEERFLOW = EXECUTOR_TYPE_DEERFLOW
    HUMAN_REVIEW = EXECUTOR_TYPE_HUMAN_REVIEW
    SYSTEM = EXECUTOR_TYPE_SYSTEM


class InterventionType(str, Enum):
    """Human intervention types."""

    APPROVE = INTERVENTION_TYPE_APPROVE
    REJECT = INTERVENTION_TYPE_REJECT
    MODIFY = INTERVENTION_TYPE_MODIFY
    COMMENT = INTERVENTION_TYPE_COMMENT
    ESCALATE = INTERVENTION_TYPE_ESCALATE


class InterventionStatus(str, Enum):
    """Human intervention lifecycle states."""

    PENDING = INTERVENTION_STATUS_PENDING
    RESOLVED = INTERVENTION_STATUS_RESOLVED
    CANCELLED = INTERVENTION_STATUS_CANCELLED


class SourceType(str, Enum):
    """Workflow trigger source types."""

    PAPERCLIP_ISSUE = SOURCE_TYPE_PAPERCLIP_ISSUE
    PORTAL = SOURCE_TYPE_PORTAL
    API = SOURCE_TYPE_API
    EVENT = SOURCE_TYPE_EVENT


class TemplateStatus(str, Enum):
    """Workflow template lifecycle states."""

    DRAFT = TEMPLATE_STATUS_DRAFT
    ACTIVE = TEMPLATE_STATUS_ACTIVE
    DEPRECATED = TEMPLATE_STATUS_DEPRECATED


class EdgeConditionType(str, Enum):
    """Workflow edge condition types."""

    ALWAYS = EDGE_CONDITION_ALWAYS
    SUCCESS = EDGE_CONDITION_SUCCESS
    FAILURE = EDGE_CONDITION_FAILURE
    MANUAL_GATE = EDGE_CONDITION_MANUAL_GATE
    EXPR = EDGE_CONDITION_EXPR


class CallbackMode(str, Enum):
    """Executor callback modes."""

    POLL = CALLBACK_MODE_POLL
    WEBHOOK = CALLBACK_MODE_WEBHOOK
    INTERRUPT = CALLBACK_MODE_INTERRUPT
