"""rpa_phase5_lease_snapshot_and_indexes

Revision ID: 00a7cf21c89d
Revises: 37efeb3d4676
Create Date: 2026-07-16 10:24:03.252333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '00a7cf21c89d'
down_revision: Union[str, None] = '37efeb3d4676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_artifacts_run_id_storage_key', 'artifacts', ['run_id', 'storage_key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND run_id IS NOT NULL'))
    op.create_index('uq_human_actions_run_id_active', 'human_actions', ['run_id'], unique=True, postgresql_where=sa.text("deleted_at IS NULL AND run_id IS NOT NULL AND status IN ('PENDING', 'OPENED')"))
    op.add_column('rpa_runs', sa.Column('command_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_index('uq_step_runs_run_id_step_id', 'step_runs', ['run_id', 'step_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('workflow_bindings', sa.Column('rpa_flow_version_id', sa.String(length=36), nullable=True))
    op.add_column('workflow_bindings', sa.Column('flow_checksum_snapshot', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_bindings', 'flow_checksum_snapshot')
    op.drop_column('workflow_bindings', 'rpa_flow_version_id')
    op.drop_index('uq_step_runs_run_id_step_id', table_name='step_runs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('rpa_runs', 'command_snapshot')
    op.drop_index('uq_human_actions_run_id_active', table_name='human_actions', postgresql_where=sa.text("deleted_at IS NULL AND run_id IS NOT NULL AND status IN ('PENDING', 'OPENED')"))
    op.drop_index('uq_artifacts_run_id_storage_key', table_name='artifacts', postgresql_where=sa.text('deleted_at IS NULL AND run_id IS NOT NULL'))
    # ### end Alembic commands ###
