INSIGHT_WINDOW_DAYS = 30
WEBUI_INDEX_MAX_BYTES = 10 * 1024 * 1024
SQLITE_QUERY_TIMEOUT_SECONDS = 5.0
CACHE_TTL_PROFILE_INSIGHT_SECONDS = 15
CACHE_TTL_CONTAINER_STATS_SECONDS = 5
CACHE_TTL_PROFILES_SECONDS = 30
